[project]
name = "course-ai-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.21.1",
    "ipykernel>=6.29.5",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.0",
]
